version: '3'
services:
  runner:
    image: gitlab/gitlab-runner:alpine-v12.2.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner:/etc/gitlab-runner:Z

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:alpine-v12.2.0
    volumes:
    - ./runner:/etc/gitlab-runner:Z
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name=HieuDepTraiRunner
    - --run-untagged=true
    - --executor=docker
    - --docker-image=docker:17.09.0-ce-dind
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_SERVER_URL=https://gitlab.com/
    - REGISTRATION_TOKEN=2313213211
    - RUNNER_TAG_LIST=hieurunner,backend